import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@components/ui/toaster";
import { ThemeProvider } from "@components/theme-provider";
import NavBar from "@components/NavBar";
import { ReactQueryProvider } from '@components/ReactQueryProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReactQueryProvider>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />

          {children}
          <Toaster />
        </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
